### ISSUE TITLE
Visual bug when showing ranks

### ISSUE THREAD

**Issue by SeifB1** [Soneliem/WAIUA#12]
I don't know if anyone else had the same bug, but when someone is immortal, it doesn't show up here, but it does show up sometimes in the previous ranks, is that normal ? 

![image](https://user-images.githubusercontent.com/92176572/136594399-9c56aa66-1cee-4f87-97cf-94aa659fc9bd.png)

**Comment by SeifB1** [comment]
Same here, the Omen level 58 was Immortal one and not Diamond 2, and Reyna wasn't Diamond 3 but Immortal 1 too
![image](https://user-images.githubusercontent.com/92176572/136603234-7e90a5b8-efa3-4135-80cf-e43e52df42ff.png)

**Comment by Soneliem** [comment]
Fixed in latest Release. Issue was detection of the max RR failed everytime.
