### ISSUE TITLE
WAIUA only shows the first 10 players when on deathmatch.

### ISSUE THREAD

**Issue by TheSylex** [Soneliem/WAIUA#15]
Maybe write a more compact view when a deathmatch is detected and show all of the players on the match.

**Comment by Soneliem** [comment]
Yes, Deathmatch support is coming. However I am still figuring out the best way to do this. Hardcoding a new page is possible but I would take some time. Instead I'm working on a solution that also supports custom games and is a lot more dynamic.

**Comment by Soneliem** [comment]
Added in v2.0.0.0 #39
