### ISSUE TITLE
Newer skins aren't showed

### ISSUE THREAD

**Issue by SoulxSlayer** [Soneliem/WAIUA#25]
The newer skins such as the RGX and Champions aren't shown.

I know the skin thingy is an extra, but it would be great to add the new ones and also, maybe a feature to show all other skins if we hit a button.

**Comment by Soneliem** [comment]
Hi, this is a known bug and the next release will fix it. In the meanwhile you should be able to manually fix it by going to settings and press force update in the bottom left.

**Comment by Soneliem** [comment]
Oops forgot to address your second point. The option to view all skins in also on my roadmap. However it will probably be after the next big update or the one after that.

**Comment by iMoltres** [comment]
Hi, this bug still exists in the latest version for the recon and RGX blue/red variants as far as I'm aware, the valorant content API doesn't provide a link for the "displayIcon" property for some of the guns, but DOES provide the "fullRender" property, switching them probably will fix it for the time being.

**Comment by iMoltres** [comment]
Lines 525 and 520 in the Main class use the displayIcon property if anyone wants to fork and change it ^^

**Comment by Soneliem** [comment]
@iMoltres Hi, the development branch already fixes it.

**Comment by Soneliem** [comment]
Fixed in v2.0.0.0 #39
