### ISSUE TITLE
Add server, map and game mode

### ISSUE THREAD

**Issue by riahc3** [Soneliem/WAIUA#26]
Hello

Just to have a complete overview of the match, it would be nice for the application to show

- Map
- Server
- Game mode 

Thank you.

**Comment by Soneliem** [comment]
![JHeJwLVWQg](https://user-images.githubusercontent.com/24221762/149761641-fd49eebe-f964-41d4-b345-0eb797d7b0f5.png)

Already in next update!

**Comment by riahc3** [comment]
Thank you very much @Soneliem

**Comment by Soneliem** [comment]
Added in v2.0.0.0 #39
