### ISSUE TITLE
Not working with BR

### ISSUE THREAD

**Issue by Bygrilinho** [Soneliem/WAIUA#3]
It's not working for me, I assume it's because there's no BR in the region selector

Had this issue with another Valorant related program before, [this may help](https://github.com/colinhartigan/valorant-rpc/issues/13#issuecomment-826462448)

**Comment by Soneliem** [comment]
> Had this issue with another Valorant related program before, [this may help](https://github.com/colinhartigan/valorant-rpc/issues/13#issuecomment-826462448)

Hi, Thanks for linking to that because it made fixing it much easier. I have made a new build that I will be posting on my discord:  https://discord.gg/X7CYCeZSRK . Not sure if it works since I'm not in br or latam

**Comment by Soneliem** [comment]
Fixed in latest release hopefully

**Comment by Bygrilinho** [comment]
Working now, thanks!
