### ISSUE TITLE
BitDefender detects install process as Variant.Bulz.6751

### ISSUE THREAD

**Issue by Ap0apsis** [Soneliem/WAIUA#4]
As the title specifies, BitDefender detects one of the executables / temp files as Variant.Bulz.6751 malware.

![image](https://user-images.githubusercontent.com/45259927/132955293-5007a78b-1e09-466d-a2f8-31ff4186f7e3.png)

**Comment by Soneliem** [comment]
False positives unfortunately, I will look into contacting bit defender and the other anti virus companies. If that doesn't work I'll think about purchasing a code signing certificate.
