### ISSUE TITLE
App does not work in competitive playlists

### ISSUE THREAD

**Issue by JonJaded** [Soneliem/WAIUA#43]
Hey I just wanted to bring this to attention. Every other casual mode the app works fine but once you try to use it in competitive, it doesn't work. Everything either infinitely loads or doesn't loads all 0's on stats.

Edit: other valorant tracker apps work like trackergg and blitz.

**Comment by Soneliem** [comment]
Hi, that ks for reporting the issue. To help further, please submit logs which are available in %localappdata%/WAIUA/logs.

**Comment by JonJaded** [comment]
[LOGS.zip](https://github.com/Soneliem/WAIUA/files/9165339/LOGS.zip)
Here are a bundle of logs. From my cursory glance, I saw a lot of them said "too many requests" but the second I queued Spike Rush the tool would work perfect fine (and automatically.)

**Comment by Soneliem** [comment]
Hi, thanks for the logs. Looks like you are v2.0.0.0 which unfortunately has a bug where the in-built updater doesn't work. Manually reinstalling will get you to the latest version.

**Comment by JonJaded** [comment]
Thanks for the swift response. I've updated. I'll join the discord and if anything I'll submit more info there. Thank you!
