### ISSUE TITLE
App doesn't connect to account anymore

### ISSUE THREAD

**Issue by TheeeEVan** [Soneliem/WAIUA#45]
I was just trying to use the app last night and it just wouldn't connect to the account anymore. Login and Authentication did nothing. Looked at the logs and looks like there's some issue with the api urls.
[log20220723.txt](https://github.com/Soneliem/WAIUA/files/9174874/log20220723.txt)

**Comment by histefanhere** [comment]
They're aware of the issues and a fix will be available soon

![image](https://user-images.githubusercontent.com/23431724/180631304-f8bf34be-2e27-4084-99cd-4cfd9088ac75.png)

**Comment by TheeeEVan** [comment]
Oh thanks I'm not in the discord, I'll just leave the issue for now since there isn't one on github yet.
