### ISSUE TITLE
Persist last game's data until a new match is found

### ISSUE THREAD

**Issue by htelsiz** [Soneliem/WAIUA#46]
Right now, after a game ends, the application displays the users in the party. I'm just wondering if it'd be feasible to keep the ranks from the last game in WAIUA visible until a new match is found -- and if not, perhaps some sort of interface for viewing the last game? 

Not sure if that'd be useful to others, but it certainly would for me. Sometimes I don't check WAIUA until the end of the game (like when the victory or defeat banners are displayed), and the existing behavior prevents me from checking ranks.

@Soneliem let me know your thoughts!

**Comment by Soneliem** [comment]
Hi there! 

> perhaps some sort of interface for viewing the last game?
This is exactly what is planned at some point. 

The main issue with this is that some info is only available during the game (skins) so these will need to be worked around. I believe that party information might also be linked to live game data.

This is planned but will take some time to implement as it uses completely different endpoints and info. For now, the only way to see info past a match is to pause the auto-refresh. 

Thanks for the Sponsor btw!

**Comment by htelsiz** [comment]
> This is planned but will take some time to implement as it uses completely different endpoints and info. For now, the only way to see info past a match is to pause the auto-refresh.

Gotcha -- good to know.
> Thanks for the Sponsor btw!

No problem. The project is neat. Thanks for building it! I suppose we can close this issue.
