### ISSUE TITLE
Name shows only for 1 second when you hover over the guns.

### ISSUE THREAD

**Issue by PrinceSangwan** [Soneliem/WAIUA#54]
The title is self-explanatory. But just in case I wasn't clear, When I hover over the skins, the name shows only for one second and then I have to hover over it again. It would be better if the name stays for as long as I hover over the skins. BTW, I love this. The only thing that slightly pisses me off is we can't see names of those who have chosen to hide it. But I understand the intention behind it.

**Comment by Soneliem** [comment]
The tooltips are supposed to stay indefinitely on hover. What you're seeing is a bug on Microsoft's side. Unfortunately I can do literally nothing to fix it. Maybe the next update might fix it when I update the framework dependencies.

**Comment by Soneliem** [comment]
Also the names is something that will never happen as a similar app, vRY got people banned because of it.
