### ISSUE TITLE
WAIUA no longer shows rank with new update.

### ISSUE THREAD

**Issue by RiceGrain1** [Soneliem/WAIUA#56]
![image](https://user-images.githubusercontent.com/102405076/213859296-493b1d55-efc7-4322-b3cc-a540923ea040.png)
WAIUA no longer shows people's rank since the new episode 6 update.

**Comment by Soneliem** [comment]
The current steps to fix this are:
1. Navigate to `%localappdata%/WAIUA/ValAPI` using file manager. 
2. Delete the `version.txt` file
3. You might also need to manually re-select your language in settings

**Comment by RiceGrain1** [comment]
> The current steps to fix this are:
> 1. Navigate to `%localappdata%/WAIUA/ValAPI` using file manager. 
> 2. Delete the `version.txt` file
> 3. You might also need to manually re-select your language in settings

Can confirm that this worked for me. Do you know what causes this issue to happen?

**Comment by Soneliem** [comment]
> > The current steps to fix this are:
> > 1. Navigate to `%localappdata%/WAIUA/ValAPI` using file manager. 
> > 2. Delete the `version.txt` file
> > 3. You might also need to manually re-select your language in settings
> 
> Can confirm that this worked for me. Do you know what causes this issue to happen? 

It's because valorant-api.com had the wrong game version for a bit. I cache the version numbers but I might remove it to prevent more issues like this.
